version: "3.8"
services:
  api:
    build: .
    ports:
      - "80:8000"
#    env_file:
#      - key.env
#    volumes:
#    - "./Backend_iSi/:/app/"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]